---
title: "Further analysis on mml with random local models"
author: "Yang (Kelvin) Li"
date: "13 March 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE, echo = F, eval = T)
if (.Platform$OS.type == "windows") {
  dir = "C:/Users/"
} else {
  dir = "/home/"
}
source(paste0(dir, "kl/Documents/PhDProjects/RStudioProjects/local2global/scripts/load_libraries.R"))
```

```{r}
randData = function(cpts, n) {
  
  dt = rbn(cpts, n)
  arities = sapply(dt, nlevels)
  vars = colnames(dt)
  lst = list(vars = vars, arities = arities, data = dt)
  return(lst)
  
}
```


```{r}
dag = randDag(7, 2)
cpts = randCPTs(dag, 2, 1)
n = sampleSize = 1000
smpl = randData(cpts, n)
varCnt = count_occurance(smpl$data, smpl$arities)
data = data.matrix(smpl$data)
arities = smpl$arities
vars = smpl$vars
target = "V1"
model = "random"
prior = "uniform"
debug = T
forward_greedy(data, arities, vars, n, target, model = model, varCnt = varCnt, prior = prior, debug = debug)
# there is a bug, for the str V6->V1, mmlcpt and mmlrand gave different scores, fix! 
```





