---
title: "scale_up_camml_using_mb"
author: "Kelvin Li"
date: "18 April 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE, echo = F, eval = T)
if (.Platform$OS.type == "windows") {
  dir = "C:/Users/"
} else {
  dir = "/home/"
}
source(paste0(dir, "kl/Documents/PhDProjects/RStudioProjects/local2global/scripts/load_libraries.R"))
library(plyr)
```

## mode generation
Generated 10 random models with 500 sample for each model. 
```{r}
n = sampleSize = 500
sd = randSeed()
set.seed(sd)
dag = randDag(30, 4)
cpts = randCPTs(dag, 5, 1)
smpl = randData(cpts, n)
filename = paste0("30_4_5_1_500_", sd)
saveRDS(dag, paste0("~/Documents/Experiments/camml_with_prior_testing/dag/dag_", filename, ".rds"))
saveRDS(cpts, paste0("~/Documents/Experiments/camml_with_prior_testing/cpts/cpts_", filename, ".rds"))
write.csv(smpl$data, paste0("~/Documents/Experiments/camml_with_prior_testing/data_csv/", filename, ".csv"), row.names=FALSE)
saveRDS(smpl$data, paste0("~/Documents/Experiments/camml_with_prior_testing/data_rds/", filename, ".rds"))
```

## camml w/o prior
Learning has been done in GUI for now.
```{r}
dagst = list.files("~/Documents/Experiments/camml_with_prior_testing/dag/")
dagsl = list.files("~/Documents/Experiments/camml_with_prior_testing/camml_no_prior/")
error = rep(0, length(dagst))
for (i in 1:length(dagst)) {
  dagt = readRDS(paste0("~/Documents/Experiments/camml_with_prior_testing/dag/", dagst[i]))
  dagl = netica2bnlearn(paste0("~/Documents/Experiments/camml_with_prior_testing/camml_no_prior/", dagsl[i]))
  dagl = parentsList2BN(dagl)
  error[i] = hamming(dagl, dagt)
}
error
mean(error)
sd(error) * 1.96 / sqrt(length(error))
```
```{r}
# a function to create false arcs 
false_arcs = function(dag, nArcs) {
  vars = bnlearn::nodes(dag)
  m = matrix(0, nArcs, 2)
  i = 1
  repeat {
    e = sample(vars, 2)
    a = is.na(row.match(e, dag$arcs))
    b = is.na(row.match(e, m))
    #cat(e, trueArc, "\n")
    if (a && b) {
      m[i, ] = e
      i = i + 1
    }
    if (i == (nArcs + 1)) break
  }
  colnames(m) = c("from", "to")
  return(m)
}
```

## format camml prior
Use true structure prior. 
```{r}
files = list.files("~/Documents/Experiments/camml_with_prior_testing/dag/")
for (i in 1:length(files)) {
  dag = readRDS(paste0("~/Documents/Experiments/camml_with_prior_testing/dag/", files[i]))
  #arcs = dag$arcs
  arcs = false_arcs(dag, 20)
  txt = cammlPrior(arcs, 0.8)
  filename = strsplit(files[i], "_")[[1]][-c(1)]
  filename = paste0(filename, collapse = "_")
  filename = paste0(strsplit(filename, ".rds")[[1]][1], ".txt")
  write_file(txt, paste0("~/Documents/Experiments/camml_with_prior_testing/prior/", filename))  
}
```

## camml w/ prior
Learning has been done in GUI for now.
```{r}
dagst = list.files("~/Documents/Experiments/camml_with_prior_testing/dag/")
dagsl = list.files("~/Documents/Experiments/camml_with_prior_testing/camml_with_false_prior/1.0/")
error = rep(0, length(dagst))
for (i in 1:6) {
  dagt = readRDS(paste0("~/Documents/Experiments/camml_with_prior_testing/dag/", dagst[i]))
  dagl = netica2bnlearn(paste0("~/Documents/Experiments/camml_with_prior_testing/camml_with_false_prior/1.0/", dagsl[i]))
  dagl = parentsList2BN(dagl)
  error[i] = hamming(dagl, dagt)
}
error
mean(error)
sd(error) * 1.96 / sqrt(length(error))
```











