---
title: "Create an R package"
author: "kl"
date: "11 July 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

creating an R package 
run command in terminal in linux os

```{r}
# sudo apt-get install libcurl4-openssl-dev libssl-dev 
install.packages("devtools")
library(devtools)
devtools::install_github("klutometis/roxygen") # install the developer version of the roxygen2 package 
library(roxygen2)
```

<!-- # 1. create your package directory  -->
<!-- create("causalbn") -->
<!-- # 2. add functions -->
<!-- # 3. add documentation -->
<!-- # 4. process your documentation -->
<!-- document() -->
<!-- # 5. install -->
<!-- setwd("../") -->
<!-- install("causalbn/") -->
<!-- # 6. install the package from github on other devices  -->
<!-- install_github("kelvinyangli/PhDProjects/causalbn", auth_token = "getThisFromMyGithub") -->
<!-- # check packages info  -->
<!-- devtools::session_info() -->

## Install package from terminal
Go to the directory that contains the package directory. In terminal, type

```{r}
# R CMD build lglbnlearn
```

## Installing an R package
To install the package, type (at the command line)
```{r}
# R CMD INSTALL lglbnlearn_0.0.0...full version number
```


